INSERT INTO pelicula(fecha_estreno, min_duracion, resumen, titulo) VALUES ('2022-02-11','116','Adaptación de la exitosa serie de videojuegos creada por Naughty Dog','Uncharted')
INSERT INTO pelicula(fecha_estreno, min_duracion, resumen, titulo) VALUES ('2021-12-03','124','Una madre soltera y sus dos hijos llegan a una pequeña ciudad, descubriendo su conexión con los cazafantasmas originales','Cazafantasmas: Más allá')
INSERT INTO pelicula(fecha_estreno, min_duracion, resumen, titulo) VALUES ('2021-12-17','148','Por primera vez en la historia cinematográfica de Spider-Man, nuestro héroe, vecino y amigo es desenmascarado','Spider-Man: No Way Home')
INSERT INTO pelicula(fecha_estreno, min_duracion, resumen, titulo) VALUES ('2019-04-26','181','Después de los eventos de Avengers: Infinty War. El universo está en ruinas debido a las acciones de Thanos, el Titán Loco. Con la ayuda de los aliados que quedaron, los Vengadores deberán reunirse una vez más para intentar deshacer sus acciones','Vengadores: Endgame')

INSERT INTO actor(`nombre`,`apellidos`, `fecha_nacimiento`, `nacionalidad`) VALUES ('Anthony','Flags','1960-08-10','Española')
INSERT INTO actor(`nombre`,`apellidos`, `fecha_nacimiento`, `nacionalidad`) VALUES ('Tom','Holland','1996-06-01','Britanica')
INSERT INTO actor(`nombre`,`apellidos`, `fecha_nacimiento`, `nacionalidad`) VALUES ('Sophia','Ali','1995-11-07','Estadounidense')
INSERT INTO actor(`nombre`,`apellidos`, `fecha_nacimiento`, `nacionalidad`) VALUES ('Paul','Rudd','1969-04-06','Estadounidense')
INSERT INTO actor(`nombre`,`apellidos`, `fecha_nacimiento`, `nacionalidad`) VALUES ('Finn','Wolfhard','2002-12-23','Canadiense')
INSERT INTO actor(`nombre`,`apellidos`, `fecha_nacimiento`, `nacionalidad`) VALUES ('Jonathan Kimble','Simmons','1955-01-09','Estadounidense')
INSERT INTO actor(`nombre`,`apellidos`, `fecha_nacimiento`, `nacionalidad`) VALUES ('Tobey','Maguire','1975-06-27','Estadounidense')
INSERT INTO actor(`nombre`,`apellidos`, `fecha_nacimiento`, `nacionalidad`) VALUES ('Robert','Downey Jr.','1965-04-04','Estadounidense')

INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('1','1')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('1','2')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('1','3')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('2','4')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('2','5')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('2','6')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('3','2')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('3','6')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('3','7')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('4','2')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('4','4')
INSERT INTO pelicula_actor(`pelicula_id`, `actor_id`) VALUES ('4','8')
